<?php
DEFINE("API_ROUTE", $_SERVER['DOCUMENT_ROOT']."/api/");
DEFINE("CONFIG_ROUTE", $_SERVER['DOCUMENT_ROOT']."/config/");
DEFINE("HTML_ROUTE", $_SERVER['DOCUMENT_ROOT']."/html/");
DEFINE("JS_ROUTE", $_SERVER['DOCUMENT_ROOT']."/js/");


?>